COPY    START   1000
FIRST   STL     RETADR
CLOOP   JSUB    RDREC
**      LDA     LENGTH
**      COMP    ZERO
**      JEQ     ENDFIL
**      JSUB    WRREC
**      J       CLOOP
ENDFIL  LDA     EOF
**      STA     BUFFER
**      LDA     EOF
**      RSUB    **
RETADR  RESW    1
LENGTH  RESW    1
BUFFER  RESB    4096
EOF     BYTE    C'EOF'
ZERO    WORD    0
**      END     FIRST